# Generated by Django 4.1.7 on 2023-02-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='raiting',
            new_name='rating',
        ),
    ]
