# Generated by Django 4.1.7 on 2023-02-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_raiting_author_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_user',
        ),
    ]
